[project]
name = "gameplan"
authors = [
    { name = "Frappe Technologies Pvt Ltd", email = "developers@frappe.io" },
]
description = "Team discussion and collaboration tool"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = ["rembg>=2.0.49,<2.1", "numpy==1.26.1", "onnxruntime==1.16.2"]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.ruff]
line-length = 110
target-version = "py310"

[tool.ruff.lint]
select = ["F", "E", "W", "I", "UP", "B"]
ignore = [
    "B017", # assertRaises(Exception) - should be more specific
    "B018", # useless expression, not assigned to anything
    "B023", # function doesn't bind loop variable - will have last iteration's value
    "B904", # raise inside except without from
    "E101", # indentation contains mixed spaces and tabs
    "E402", # module level import not at top of file
    "E501", # line too long
    "E741", # ambiguous variable name
    "F401", # "unused" imports
    "F403", # can't detect undefined names from * import
    "F405", # can't detect undefined names from * import
    "F722", # syntax error in forward type annotation
    "F821", # undefined name
    "W191", # indentation contains tabs
]

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
docstring-code-format = true
